Fixed a bug that was causing incorrect Main-Class to be included in the MANIFEST.MF within web-develop-SNAPSHOT.jar.
Symptom:
[~/project/MultiBitExchange :)   (develop)]  java -jar target/web-develop-SNAPSHOT.jar server mbexchange-demo.yml
Error: Could not find or load main class org.multibit.exchange.infrastructure.adaptor.api.MultiBitExchangeApiWebService